name: Deploy Chatbot to EC2

on: [push]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Restart Chatbot Service
        run: |
          sudo systemctl restart chatbot